name: Update docs

on:
  workflow_run:
    workflows: ["Tag and publish"]
    types:
      - completed

jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.SERVICE_TOKEN }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Generate new rst files
      run: | 
        python -m pip install -e .[dev] --no-cache-dir
    - name: Build documentation
      run: |
        sphinx-apidoc -o docs/source/ src
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "ci: update docs [skip actions]"
        add: '["*.rst"]'